---

stages:
  - check
  - test
  - build
  - production


before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -U -r requirements.txt
  - flake8 --version
  - pylint --version
  - black --version
  - echo isort $(isort --version-number)


check:
  stage: check
  image: python:3.9.6-slim
  script:
    - isort --check --diff *.py lib/*.py tests/*.py
    - black --check *.py lib/*.py tests/*.py
    - flake8 *.py lib/*.py tests/*.py
    - pylint *.py lib/*.py tests/*.py
  cache:
    key: build-cache
    paths:
        - .cache/pip
        - venv/

test:
  stage: test
  image: python:3.9.6-slim
  script:
    - pytest -v --cov=lib --cov-report term-missing tests/
    - cat data/easy.txt
    - python solve_sudoku.py data/easy.txt
    - python solve_sudoku.py data/easy.json
    - python solve_sudoku.py -v data/easy.txt
    - python solve_sudoku.py -h
    - python solve_sudoku.py --version
  cache:
    key: build-cache
    paths:
      - .cache/pip
      - venv/

build:
    image: docker:0.1.0
    stage: build
    services:
        - docker:dind
    before_script:
        - echo $CI_BUILD_TOKEN | docker login -u "arzukhanna" --password-stdin python-sudoku
    script:
        - docker build --pull --tag arzukhanna/python-sudoku 485c8c2f.
        - docker push "arzukhanna/python-sudoku"

production:
  image: docker:0.1.0
  stage: production
  services:
    - docker:dind
  before_script:
    - echo $CI_BUILD_TOKEN | docker login -u arzukhanna --password-stdin python-sudoku
  script:
    - docker pull arzukhanna/python-sudoku .
    - run arzukhanna/python-sudoku:0.1.0
