---

image: python:3.9.4-slim

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -U -r requirements.txt
  - flake8 --version
  - pylint --version
  - black --version
  - echo isort $(isort --version-number)

build:
  stage: build
  script:
    - isort --check --diff *.py lib/*.py tests/*.py
    - black --check *.py lib/*.py tests/*.py
    - flake8 *.py lib/*.py tests/*.py
    - pylint *.py lib/*.py tests/*.py
    - pytest -v tests
    - pytest -v --cov=lib --cov-report term-missing tests/
    - cat data/easy.txt
    - python solve_sudoku.py data/easy.txt
    - python solve_sudoku.py -h
    - python solve_sudoku.py --version
